//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleCRUD.Service
{
    using System;
    using System.Collections.Generic;

    public partial class VehicleModel : IVehicleModel
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Abrv { get; set; }
        public System.Guid MakeId { get; set; }

        public virtual VehicleMake VehicleMake { get; set; }
    }
}
