//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleCRUD.Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class VehiclesDbEntities : DbContext, IVehiclesDbEntities
    {
        public VehiclesDbEntities()
            : base("name=VehiclesDbEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<VehicleMake> VehicleMakes { get; set; }
        public virtual DbSet<VehicleModel> VehicleModels { get; set; }
    }
}
